spring:
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active:default}
      label: ${spring.application.name}
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ws
        instance-id: ${spring.cloud.consul.discovery.service-name}-1
  config:
    import: "optional:configserver:http://localhost:8888/"
  application:
    name: ws
  datasource:
    url: jdbc:postgresql://localhost:9999/postgres?currentSchema=mydb
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    defer-datasource-initialization: false
    show-sql: true
    generate-ddl: false

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baselineOnMigrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
    default-schema: mydb
    schemas: mydb
server:
  port: 8081

kn:
  soap:
    enabled: true

